apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "xendit-node-app.fullname" . }}-{{ .Values.version }}
  namespace: {{ .Values.environment }}
  labels:
    app: {{ template "xendit-node-app.fullname" . }}-{{ .Values.version }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app:  {{ template "xendit-node-app.fullname" . }}-{{ .Values.version }}
  template:
    metadata:
      labels:
        app: {{ template "xendit-node-app.fullname" . }}-{{ .Values.version }}
{{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      containers:
      - name: {{ template "xendit-node-app.fullname" . }}-{{ .Values.version }}
        image: "{{ .Values.image }}"
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 35 
          periodSeconds: 20
        livenessProbe:
          tcpSocket:
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 40
          periodSeconds: 20
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        {{- if .Values.envs.NAME }}
        - name: NAME
          value: {{ .Values.envs.NAME | quote }}
        {{- end }}
        {{- if .Values.envs.MONGO_HOST }}
        - name: MONGO_HOST
          value: {{ .Values.envs.MONGO_HOST | quote }}
        {{- end }}
        ports:
        - name: {{ .Values.service.name }}
          containerPort: {{ .Values.service.targetPort }}
        volumeMounts:
        - name: tz-config
          mountPath: {{ .Values.tzpath | quote }}
      priorityClassName: {{ .Values.priorityClass }}
      volumes:
      - name: tz-config
        hostPath:
          path: {{ .Values.tzcountry }}
